name: API Request
description: Create an API request for Quilt Standard Libraries.
labels: [enhancement, help wanted, t: new api]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your API request! If you want to discuss your request, join us on [Discord](https://discord.quiltmc.org).

  - type: textarea
    id: description
    attributes:
      label: Describe what API(s) you want.
      description: "Describe what API you believe QSL should implement. What does the API do? Is there a similar implementation, and if so, how should QSL differ from it? The more detailed your request is the easier it will be for people to begin implementation of the API."
    validations:
      required: true

  - type: textarea
    id: library-or-module
    attributes:
      label: Where does your API fit into QSL's structure? Which library and module? Does this add a new library or module?
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Add any other information about your API request here."
